### ISSUE TITLE
Add Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [GautamAnjali569/grovvin#8]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (WOB24 Contribution)

**Comment by KiranBaliga** [comment]
@GautamAnjali569 Please assign to me if interested. Thank you!

**Comment by snehas-05** [comment]
heyy I would love to add this feature. @GautamAnjali569 please assign me this task

**Comment by KiranBaliga** [comment]
Closing due to no response.
